# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532c346a775e4b1bf5ad81a3da7026c43cc4d9d91f65d0c560aba380e1587b1dcdf7b13990bb3f75863acf8ac38169738e36386f82afd69c056cf1ffa7f56591

test:
  secret_key_base: 643ce4d20773019db6027ec1b0e2de8767e9f83db0f3af37257edb61e4b4c2b4c4b6dc9b19a028e7a9cb53507154f5c8942480cc7de9f2d40b2000e388fff2bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
